In [7]:
import numpy as np
n=24
p=np.random.uniform(1,20,n)
print(p)
p=p/(sum(p))
a=['a','b','c','a1','b1','c1','a2','b2','c2','a3','b3','c3','a4','b4','c4','a5','b5','c5','a6','b6','c6','a7','b7','c7']
np.random.choice(a,3,replace=False,p=p)

[ 3.60868586 15.01151368  7.68889635 16.10384597  8.43054927 11.65031418
 11.21798828 15.63913161  3.25809009 12.52548223  9.41300516 15.55317997
 14.00837517  9.90095347 16.47949948  9.39479412 10.76820719 15.64138983
  8.99596491 12.66352992 14.7810863   1.44680203  6.21106527  9.20197574]


array(['a3', 'c7', 'b4'], dtype='<U2')

In [13]:
k=1/4
p=np.random.binomial(1,k,n)
print(p)

[0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]


In [22]:
def updateP(p,k):
    for i in range(p.size):
        if p[i]==0:
            p[i]=np.random.binomial(1,k,1)
        else:
            p[i]=np.random.binomial(1,1-k,1)

In [28]:
k=1/4
p=np.random.binomial(1,k,n)
print(p)
for i in range(100):
    updateP(p,k)
    print(p)

[0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1]
[0 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1]
[0 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 0]
[0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0]
[0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1 0 0 0]
[0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1]
[0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 0 1]
[0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1]
[0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1]
[0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 0 1]
[1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 1]
[1 0 0 1 1 0 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 0 1]
[1 0 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0]
[1 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0]
[1 0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 1 0 0 1 0 0 1]
[1 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1]
[1 1 0 0 0 1 1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 1 1 1]
[1 1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 1 1 1 0 1 1]
[1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1]
[1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1]


In [3]:
import utils.ss_transforms as sstr
from steps import Args
from steps import createServerStep1, createServerStep2, createServerStep3, createServerStep4

In [5]:
args=Args(bs=4,num_epochs=20,num_rounds=5,clients_per_round=3,distribution='binomial',distributionParam=0.25)
t=sstr.Resize((540,960))
server=createServerStep2(args,t,t)
for i in range(100):
    print(server.clientsDistribution.astype(int))
    server.select_clients()
    server.updateClientProb()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0]
[1 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 0 1]
[1 1 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0]
[0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0]
[1 0 1 0 1 0 0 1 1 0 1 0 0 0 0 1 0 1 1 0 0 1 1 0]
[1 1 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 1 1 1]
[0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 1 0 1 1 1 0]
[0 0 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 0 1]
[0 0 0 0 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 1]
[1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 1 1]
[1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 1 1 0]
[1 0 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1]
[1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 1]
[0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 1]
[1 1 0 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0 1 1]
[0 1 1 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 1]
[1 1 1 0 0 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 0 1 1]
[1 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1]
[1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0 1 1 0 1 1 1 1]
